In [2]:
import pandas as pd
df=pd.read_csv(r"C:\Users\HP\Desktop\DATA ANALYSIS\11 PROJECT ELECTRICITY CONSUMPTION IN UK 2009-2024\historic_demand_2009_2024.csv")

In [4]:
df

,Unnamed: 0,settlement_date,settlement_period,nd,tsd,england_wales_demand,embedded_wind_generation,embedded_wind_capacity,embedded_solar_generation,embedded_solar_capacity,...,britned_flow,moyle_flow,east_west_flow,nemo_flow,nsl_flow,eleclink_flow,scottish_transfer,viking_flow,greenlink_flow,is_holiday
0,0,2009-01-01,1,37910,38704,33939,54,1403,0,0,...,0,-161,0,0,NaN,NaN,NaN,NaN,NaN,1
1,1,2009-01-01,2,38047,38964,34072,53,1403,0,0,...,0,-160,0,0,NaN,NaN,NaN,NaN,NaN,1
2,2,2009-01-01,3,37380,38651,33615,53,1403,0,0,...,0,-160,0,0,NaN,NaN,NaN,NaN,NaN,1
3,3,2009-01-01,4,36426,37775,32526,50,1403,0,0,...,0,-160,0,0,NaN,NaN,NaN,NaN,NaN,1
4,4,2009-01-01,5,35687,37298,31877,50,1403,0,0,...,0,-160,0,0,NaN,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279259,279259,2024-12-05,44,29114,31431,27212,5377,6622,0,17194,...,1003,-450,-531,999,1397.0,0.0,4878.0,1422.0,0.0,0
279260,279260,2024-12-05,45,27204,29846,25477,5486,6622,0,17194,...,1002,-450,-531,949,1397.0,0.0,4849.0,1422.0,0.0,0
279261,279261,2024-12-05,46,26006,28805,24428,5594,6622,0,17194,...,997,-450,-531,943,1376.0,0.0,4666.0,1414.0,0.0,0
279262,279262,2024-12-05,47,23908,26825,22590,5575,6622,0,17194,...,280,-450,-522,338,1040.0,0.0,4771.0,875.0,0.0,0
279263,279263,2024-12-05,48,23217,26133,21958,5556,6622,0,17194,...,218,-450,-530,292,993.0,0.0,4687.0,823.0,0.0,0

In [5]:
df.shape

(279264, 24)

In [6]:
df.dtypes

Unnamed: 0                     int64
settlement_date               object
settlement_period              int64
nd                             int64
tsd                            int64
england_wales_demand           int64
embedded_wind_generation       int64
embedded_wind_capacity         int64
embedded_solar_generation      int64
embedded_solar_capacity        int64
non_bm_stor                    int64
pump_storage_pumping           int64
ifa_flow                       int64
ifa2_flow                      int64
britned_flow                   int64
moyle_flow                     int64
east_west_flow                 int64
nemo_flow                      int64
nsl_flow                     float64
eleclink_flow                float64
scottish_transfer            float64
viking_flow                  float64
greenlink_flow               float64
is_holiday                     int64
dtype: object

In [7]:
df.isnull().sum()

Unnamed: 0                        0
settlement_date                   0
settlement_period                 0
nd                                0
tsd                               0
england_wales_demand              0
embedded_wind_generation          0
embedded_wind_capacity            0
embedded_solar_generation         0
embedded_solar_capacity           0
non_bm_stor                       0
pump_storage_pumping              0
ifa_flow                          0
ifa2_flow                         0
britned_flow                      0
moyle_flow                        0
east_west_flow                    0
nemo_flow                         0
nsl_flow                     175296
eleclink_flow                175296
scottish_transfer            245424
viking_flow                  245424
greenlink_flow               262944
is_holiday                        0
dtype: int64

In [8]:
df=df.drop(columns=['nsl_flow','eleclink_flow','scottish_transfer','viking_flow','greenlink_flow'])

In [9]:
df

,Unnamed: 0,settlement_date,settlement_period,nd,tsd,england_wales_demand,embedded_wind_generation,embedded_wind_capacity,embedded_solar_generation,embedded_solar_capacity,non_bm_stor,pump_storage_pumping,ifa_flow,ifa2_flow,britned_flow,moyle_flow,east_west_flow,nemo_flow,is_holiday
0,0,2009-01-01,1,37910,38704,33939,54,1403,0,0,0,33,2002,0,0,-161,0,0,1
1,1,2009-01-01,2,38047,38964,34072,53,1403,0,0,0,157,2002,0,0,-160,0,0,1
2,2,2009-01-01,3,37380,38651,33615,53,1403,0,0,0,511,2002,0,0,-160,0,0,1
3,3,2009-01-01,4,36426,37775,32526,50,1403,0,0,0,589,1772,0,0,-160,0,0,1
4,4,2009-01-01,5,35687,37298,31877,50,1403,0,0,0,851,1753,0,0,-160,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279259,279259,2024-12-05,44,29114,31431,27212,5377,6622,0,17194,0,736,558,758,1003,-450,-531,999,0
279260,279260,2024-12-05,45,27204,29846,25477,5486,6622,0,17194,0,868,-193,263,1002,-450,-531,949,0
279261,279261,2024-12-05,46,26006,28805,24428,5594,6622,0,17194,0,944,-274,211,997,-450,-531,943,0
279262,279262,2024-12-05,47,23908,26825,22590,5575,6622,0,17194,0,864,-404,-77,280,-450,-522,338,0
279263,279263,2024-12-05,48,23217,26133,21958,5556,6622,0,17194,0,820,-415,-101,218,-450,-530,292,0

In [10]:
df.isnull().sum()

Unnamed: 0                   0
settlement_date              0
settlement_period            0
nd                           0
tsd                          0
england_wales_demand         0
embedded_wind_generation     0
embedded_wind_capacity       0
embedded_solar_generation    0
embedded_solar_capacity      0
non_bm_stor                  0
pump_storage_pumping         0
ifa_flow                     0
ifa2_flow                    0
britned_flow                 0
moyle_flow                   0
east_west_flow               0
nemo_flow                    0
is_holiday                   0
dtype: int64

In [31]:
df=pd.read_csv(r"C:\Users\HP\Desktop\DATA ANALYSIS\11 PROJECT ELECTRICITY CONSUMPTION IN UK 2009-2024\historic_demand_2009_2024_noNaN.csv")

In [4]:
df

,settlement_date,settlement_period,period_hour,nd,tsd,england_wales_demand,embedded_wind_generation,embedded_wind_capacity,embedded_solar_generation,embedded_solar_capacity,non_bm_stor,pump_storage_pumping,ifa_flow,ifa2_flow,britned_flow,moyle_flow,east_west_flow,nemo_flow,is_holiday
0,1/1/2009 0:00,1,0:00:00,37910,38704,33939,54,1403,0,0,0,33,2002,0,0,-161,0,0,1
1,1/1/2009 0:30,2,0:30:00,38047,38964,34072,53,1403,0,0,0,157,2002,0,0,-160,0,0,1
2,1/1/2009 1:00,3,1:00:00,37380,38651,33615,53,1403,0,0,0,511,2002,0,0,-160,0,0,1
3,1/1/2009 1:30,4,1:30:00,36426,37775,32526,50,1403,0,0,0,589,1772,0,0,-160,0,0,1
4,1/1/2009 2:00,5,2:00:00,35687,37298,31877,50,1403,0,0,0,851,1753,0,0,-160,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278507,12/5/2024 21:30,44,21:30:00,29114,31431,27212,5377,6622,0,17194,0,736,558,758,1003,-450,-531,999,0
278508,12/5/2024 22:00,45,22:00:00,27204,29846,25477,5486,6622,0,17194,0,868,-193,263,1002,-450,-531,949,0
278509,12/5/2024 22:30,46,22:30:00,26006,28805,24428,5594,6622,0,17194,0,944,-274,211,997,-450,-531,943,0
278510,12/5/2024 23:00,47,23:00:00,23908,26825,22590,5575,6622,0,17194,0,864,-404,-77,280,-450,-522,338,0
278511,12/5/2024 23:30,48,23:30:00,23217,26133,21958,5556,6622,0,17194,0,820,-415,-101,218,-450,-530,292,0

In [32]:
df['settlement_date']=pd.to_datetime(df['settlement_date'],errors='coerce')

In [6]:
df.dtypes

settlement_date              datetime64[ns]
settlement_period                     int64
period_hour                          object
nd                                    int64
tsd                                   int64
england_wales_demand                  int64
embedded_wind_generation              int64
embedded_wind_capacity                int64
embedded_solar_generation             int64
embedded_solar_capacity               int64
non_bm_stor                           int64
pump_storage_pumping                  int64
ifa_flow                              int64
ifa2_flow                             int64
britned_flow                          int64
moyle_flow                            int64
east_west_flow                        int64
nemo_flow                             int64
is_holiday                            int64
dtype: object

In [6]:
df

,settlement_date,settlement_period,period_hour,nd,tsd,england_wales_demand,embedded_wind_generation,embedded_wind_capacity,embedded_solar_generation,embedded_solar_capacity,non_bm_stor,pump_storage_pumping,ifa_flow,ifa2_flow,britned_flow,moyle_flow,east_west_flow,nemo_flow,is_holiday
0,2009-01-01 00:00:00,1,0:00:00,37910,38704,33939,54,1403,0,0,0,33,2002,0,0,-161,0,0,1
1,2009-01-01 00:30:00,2,0:30:00,38047,38964,34072,53,1403,0,0,0,157,2002,0,0,-160,0,0,1
2,2009-01-01 01:00:00,3,1:00:00,37380,38651,33615,53,1403,0,0,0,511,2002,0,0,-160,0,0,1
3,2009-01-01 01:30:00,4,1:30:00,36426,37775,32526,50,1403,0,0,0,589,1772,0,0,-160,0,0,1
4,2009-01-01 02:00:00,5,2:00:00,35687,37298,31877,50,1403,0,0,0,851,1753,0,0,-160,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278507,2024-12-05 21:30:00,44,21:30:00,29114,31431,27212,5377,6622,0,17194,0,736,558,758,1003,-450,-531,999,0
278508,2024-12-05 22:00:00,45,22:00:00,27204,29846,25477,5486,6622,0,17194,0,868,-193,263,1002,-450,-531,949,0
278509,2024-12-05 22:30:00,46,22:30:00,26006,28805,24428,5594,6622,0,17194,0,944,-274,211,997,-450,-531,943,0
278510,2024-12-05 23:00:00,47,23:00:00,23908,26825,22590,5575,6622,0,17194,0,864,-404,-77,280,-450,-522,338,0
278511,2024-12-05 23:30:00,48,23:30:00,23217,26133,21958,5556,6622,0,17194,0,820,-415,-101,218,-450,-530,292,0

In [33]:
check_duplicates=df['settlement_date'].duplicated().any()

In [34]:
print(check_duplicates)

False

In [35]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('\\','_')

In [10]:
df

,settlement_date,settlement_period,period_hour,nd,tsd,england_wales_demand,embedded_wind_generation,embedded_wind_capacity,embedded_solar_generation,embedded_solar_capacity,non_bm_stor,pump_storage_pumping,ifa_flow,ifa2_flow,britned_flow,moyle_flow,east_west_flow,nemo_flow,is_holiday
0,2009-01-01 00:00:00,1,0:00:00,37910,38704,33939,54,1403,0,0,0,33,2002,0,0,-161,0,0,1
1,2009-01-01 00:30:00,2,0:30:00,38047,38964,34072,53,1403,0,0,0,157,2002,0,0,-160,0,0,1
2,2009-01-01 01:00:00,3,1:00:00,37380,38651,33615,53,1403,0,0,0,511,2002,0,0,-160,0,0,1
3,2009-01-01 01:30:00,4,1:30:00,36426,37775,32526,50,1403,0,0,0,589,1772,0,0,-160,0,0,1
4,2009-01-01 02:00:00,5,2:00:00,35687,37298,31877,50,1403,0,0,0,851,1753,0,0,-160,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278507,2024-12-05 21:30:00,44,21:30:00,29114,31431,27212,5377,6622,0,17194,0,736,558,758,1003,-450,-531,999,0
278508,2024-12-05 22:00:00,45,22:00:00,27204,29846,25477,5486,6622,0,17194,0,868,-193,263,1002,-450,-531,949,0
278509,2024-12-05 22:30:00,46,22:30:00,26006,28805,24428,5594,6622,0,17194,0,944,-274,211,997,-450,-531,943,0
278510,2024-12-05 23:00:00,47,23:00:00,23908,26825,22590,5575,6622,0,17194,0,864,-404,-77,280,-450,-522,338,0
278511,2024-12-05 23:30:00,48,23:30:00,23217,26133,21958,5556,6622,0,17194,0,820,-415,-101,218,-450,-530,292,0

In [36]:
pip install pymysql sqlalchemy

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

Requirement already satisfied: pymysql in c:\users\hp\appdata\roaming\python\python313\site-packages (1.1.2)
Requirement already satisfied: sqlalchemy in c:\programdata\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)

In [37]:
import sqlalchemy as sal
import urllib.parse

In [38]:
username='root'
password='TinsonSeethu21@'
host='localhost'
port=3306
database='airline'

In [39]:
password_encoded=urllib.parse.quote_plus(password)

In [40]:
engine=sal.create_engine(f"mysql+mysqlconnector://{username}:{password_encoded}@{host}:{port}/{database}")

In [41]:
try:
    conn=engine.connect()
    print("connect successfully")
    conn.close()
except Excemption as e:
    print("connection failed:",e)

connect successfully

In [42]:
conn=engine.connect()

In [ ]:
conn=engine.connect()
df.to_sql('ele_consumption',con=conn,index=False,if_exists='replace')
conn.close()

In [ ]:
conn = engine.connect()
df.to_sql(
    'ele_consumption',
    con=conn,
    index=False,
    if_exists='replace'
)

conn.commit()  # COMMIT the transaction
conn.close()

In [ ]:
df.to_sql(
    'ele_consumption',
    con=engine,      # pass engine, not connection
    index=False,
    if_exists='replace'
)

In [43]:
df.to_sql(
    'ele_consumption', 
    con=engine, 
    index=False, 
    if_exists='replace', # Creates the table fresh
    chunksize=5000       # Moves 5,000 rows at a time until all 280,000 are done
)
print("Upload Complete!")

Upload Complete!

In [19]:
df

,settlement_date,settlement_period,period_hour,nd,tsd,england_wales_demand,embedded_wind_generation,embedded_wind_capacity,embedded_solar_generation,embedded_solar_capacity,non_bm_stor,pump_storage_pumping,ifa_flow,ifa2_flow,britned_flow,moyle_flow,east_west_flow,nemo_flow,is_holiday
0,2009-01-01 00:00:00,1,0:00:00,37910,38704,33939,54,1403,0,0,0,33,2002,0,0,-161,0,0,1
1,2009-01-01 00:30:00,2,0:30:00,38047,38964,34072,53,1403,0,0,0,157,2002,0,0,-160,0,0,1
2,2009-01-01 01:00:00,3,1:00:00,37380,38651,33615,53,1403,0,0,0,511,2002,0,0,-160,0,0,1
3,2009-01-01 01:30:00,4,1:30:00,36426,37775,32526,50,1403,0,0,0,589,1772,0,0,-160,0,0,1
4,2009-01-01 02:00:00,5,2:00:00,35687,37298,31877,50,1403,0,0,0,851,1753,0,0,-160,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278507,2024-12-05 21:30:00,44,21:30:00,29114,31431,27212,5377,6622,0,17194,0,736,558,758,1003,-450,-531,999,0
278508,2024-12-05 22:00:00,45,22:00:00,27204,29846,25477,5486,6622,0,17194,0,868,-193,263,1002,-450,-531,949,0
278509,2024-12-05 22:30:00,46,22:30:00,26006,28805,24428,5594,6622,0,17194,0,944,-274,211,997,-450,-531,943,0
278510,2024-12-05 23:00:00,47,23:00:00,23908,26825,22590,5575,6622,0,17194,0,864,-404,-77,280,-450,-522,338,0
278511,2024-12-05 23:30:00,48,23:30:00,23217,26133,21958,5556,6622,0,17194,0,820,-415,-101,218,-450,-530,292,0

In [44]:
df = df.sort_values("settlement_date")

In [45]:
df["hour"] = df["settlement_date"].dt.hour
df["dayofweek"] = df["settlement_date"].dt.dayofweek
df["month"] = df["settlement_date"].dt.month

In [46]:
pip install xgboost

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

Requirement already satisfied: xgboost in c:\users\hp\appdata\roaming\python\python313\site-packages (3.2.0)
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (from xgboost) (2.1.3)
Requirement already satisfied: scipy in c:\programdata\anaconda3\lib\site-packages (from xgboost) (1.15.3)

In [28]:
pip install matplotlib

Note: you may need to restart the kernel to use updated packages.Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in c:\programdata\anaconda3\lib\site-packages (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy>=1.23 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (2.1.3)
Requirement already satisfied: packaging>=20.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

In [47]:
import pandas as pd
import matplotlib
import numpy as np
import xgboost as xgb



df['settlement_date'] = pd.to_datetime(df['settlement_date'])
df.set_index('settlement_date', inplace=True)

last_date = df.index[-1]
future_dates = pd.date_range(start=last_date + pd.Timedelta(minutes=30), periods=1488, freq='30min')
future = pd.DataFrame(index=future_dates)
future.index.name = 'settlement_date'

future['period_hour'] = future.index.hour
future['day_of_week'] = future.index.dayofweek
future['month'] = future.index.month

future['is_holiday'] = 0  

demand_history = df['england_wales_demand'].tolist()[-48:]  


df['period_hour'] = df.index.hour
df['day_of_week'] = df.index.dayofweek
df['month'] = df.index.month
df['is_holiday'] = 0  
df['demand_lag_1'] = df['england_wales_demand'].shift(1)
df['demand_lag_48'] = df['england_wales_demand'].shift(48)
df.dropna(inplace=True)

features = ['period_hour','day_of_week','month','is_holiday','demand_lag_1','demand_lag_48']
X_train = df[features]
y_train = df['england_wales_demand']

model = xgb.XGBRegressor(n_estimators=500, learning_rate=0.05, max_depth=6)
model.fit(X_train, y_train)

predictions = []

for i in range(len(future)):
    row = future.iloc[i].copy()
    row['demand_lag_1'] = demand_history[-1]
    row['demand_lag_48'] = demand_history[-48]

    pred = model.predict(row[features].values.reshape(1, -1))[0]
    predictions.append(pred)

    demand_history.append(pred)

future['predicted_demand'] = predictions

print(future.head())

                     period_hour  day_of_week  month  is_holiday  \
settlement_date
2024-12-06 00:00:00            0            4     12           0
2024-12-06 00:30:00            0            4     12           0
2024-12-06 01:00:00            1            4     12           0
2024-12-06 01:30:00            1            4     12           0
2024-12-06 02:00:00            2            4     12           0

                     predicted_demand
settlement_date
2024-12-06 00:00:00      21940.132812
2024-12-06 00:30:00      22022.308594
2024-12-06 01:00:00      21514.619141
2024-12-06 01:30:00      21012.128906
2024-12-06 02:00:00      20554.962891